CREATE DATABASE doingsdone DEFAULT CHARACTER SET utf8 DEFAULT COLLATE utf8_general_ci;

USE doingsdone;

CREATE TABLE user (
  id INT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
  dt_add DATETIME DEFAULT CURRENT_TIMESTAMP,
  email VARCHAR(128) NOT NULL,
  name CHAR(64) NOT NULL,
  password VARCHAR(255) NOT NULL
);

CREATE TABLE project (
  id INT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
  name VARCHAR(128) NOT NULL,
  user_id INT UNSIGNED NOT NULL
);

CREATE TABLE task (
  id INT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
  dt_add DATETIME DEFAULT CURRENT_TIMESTAMP,
  status BOOL DEFAULT 0,
  title VARCHAR(128) NOT NULL,
  file VARCHAR(255),
  dt_end DATETIME,
  user_id INT UNSIGNED NOT NULL,
  project_id INT UNSIGNED NOT NULL
);

ALTER TABLE project
  ADD FOREIGN KEY (user_id) REFERENCES user (id) ON UPDATE CASCADE ON DELETE CASCADE;
ALTER TABLE task
  ADD FOREIGN KEY (user_id) REFERENCES user (id) ON UPDATE CASCADE ON DELETE CASCADE,
  ADD FOREIGN KEY (project_id) REFERENCES project (id) ON UPDATE CASCADE ON DELETE CASCADE;

